# Generated by Django 4.2.7 on 2023-11-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.categorymodel",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="birth_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=1
            ),
        ),
    ]
