version: '3.11'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    restart: always
    build:
      context: .
    image: app:django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_DB_HOST: ${POSTGRES_HOST}
      DJANGO_DB_PORT: ${POSTGRES_PORT}
      DJANGO_DB_NAME: ${POSTGRES_DB}
      DJANGO_DB_USER: ${POSTGRES_USER}
      DJANGO_DB_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      SENDER_EMAIL: ${SENDER_EMAIL}
      REDIS_URL: ${REDIS_URL}
    links:
      - postgres

  celery:
    restart: always
    build:
      context: .
    container_name: celery
    command: celery -A main_app.celery:app worker --loglevel=info
    volumes:
      - ./:/celery
    depends_on:
      - postgres
      - redis
      - app
    environment:
      DJANGO_DB_HOST: ${POSTGRES_HOST}
      DJANGO_DB_PORT: ${POSTGRES_PORT}
      DJANGO_DB_NAME: ${POSTGRES_DB}
      DJANGO_DB_USER: ${POSTGRES_USER}
      DJANGO_DB_PASSWORD: ${POSTGRES_PASSWORD}
      CELERY_BROKER_URL: ${REDIS_URL}/1
